# Generated by Django 5.2.1 on 2025-07-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuisinePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='cuisine_banners/')),
            ],
            options={
                'verbose_name': 'Cuisine Page Content',
                'verbose_name_plural': 'Cuisine Page Contents',
            },
        ),
    ]
