# Generated by Django 5.2.1 on 2025-07-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisinepagecontent',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
