# Generated by Django 5.2.12 on 2026-04-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('case_type', models.CharField(choices=[('criminal', 'Criminal Law'), ('civil', 'Civil Law'), ('family', 'Family Law'), ('corporate', 'Corporate Law'), ('property', 'Property Law'), ('tax', 'Tax Law'), ('employment', 'Employment Law'), ('intellectual', 'Intellectual Property')], max_length=50)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=15)),
                ('court_location', models.CharField(blank=True, max_length=255, null=True)),
                ('opposing_party', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
