# Generated by Django 5.2.12 on 2026-04-18 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_courtupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='against_disputes', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
