# Generated by Django 5.2.1 on 2025-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantownerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurantownerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantownerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/restaurant_logos/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='timings',
            field=models.CharField(max_length=100),
        ),
    ]
