# Generated by Django 5.2.1 on 2025-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantownerprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
