# Generated by Django 5.2.1 on 2025-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantimage',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
