# Generated by Django 5.2.1 on 2025-07-18 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_menuitem_restaurant_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
