# Generated by Django 5.2.1 on 2025-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_restaurantapprovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantapprovalrequest',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
