# Generated by Django 5.2.1 on 2025-09-18 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantownerprofile',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profiles', to='restaurants.restaurant'),
        ),
    ]
