# Generated by Django 5.2.1 on 2025-09-20 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_alter_restaurantownerprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantownerprofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='restaurantownerprofile',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantownerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
