# Generated by Django 5.2.1 on 2025-09-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0029_restaurantuservisit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantuservisit',
            unique_together=set(),
        ),
    ]
