# Generated by Django 5.2.1 on 2025-09-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0030_alter_restaurantuservisit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('system', 'System')], default='medium', max_length=10),
        ),
    ]
