# Generated by Django 5.2.12 on 2026-04-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('profiles', '0003_remove_clientprofile_id_proof_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='law_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.lawfirmprofile'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('fir', 'FIR Document'), ('notice', 'Notice/Agreement'), ('evidence', 'Evidence Document'), ('correspondence', 'Correspondence'), ('id_proof', 'ID Proof'), ('bar_council_certificate', 'Bar Council Certificate'), ('firm_registration', 'Firm Registration Proof'), ('lawyer_id_proof', 'Lawyer ID Proof'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
