# Generated by Django 5.2.12 on 2026-04-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='id_proof_document',
        ),
        migrations.RemoveField(
            model_name='lawfirmprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lawfirmprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='lawfirmprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='data_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_proof_document_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_proof_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_proof_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id_proof_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='primary_lawyer_bar_council_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='primary_lawyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='primary_lawyer_specialization',
            field=models.CharField(blank=True, choices=[('corporate', 'Corporate Law'), ('criminal', 'Criminal Law'), ('family', 'Family Law'), ('intellectual', 'Intellectual Property'), ('tax', 'Tax Law'), ('labor', 'Labor Law'), ('civil', 'Civil Litigation'), ('immigration', 'Immigration Law')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='primary_lawyer_years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='total_cases_handled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='total_lawyers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirmprofile',
            name='firm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirmprofile',
            name='registration_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('partner', 'Partner'), ('senior_advocate', 'Senior Advocate'), ('associate', 'Associate'), ('legal_assistant', 'Legal Assistant'), ('paralegal', 'Paralegal')], max_length=50)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='profiles.lawfirmprofile')),
            ],
        ),
    ]
