# Generated by Django 5.2.12 on 2026-04-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_clientprofile_id_proof_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirmprofile',
            name='experience',
            field=models.CharField(blank=True, choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('11-15', '11-15 years'), ('15+', '15+ years')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lawfirmprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
