# Generated by Django 5.2.12 on 2026-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_lawfirmprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirmprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_submitted', 'Not Submitted')], default='pending', max_length=15),
        ),
    ]
