# Generated by Django 5.2.12 on 2026-10-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_adminprofile_secret_key_hash"),
        ("profiles", "0005_alter_lawfirmprofile_status"),
    ]

    operations = []
