# Generated by Django 5.2.12 on 2026-10-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_merge_20261005_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawfirmprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("not_submitted", "Not Submitted"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
